sudo: false
language: node_js
node_js:
  - node

install:
  - npm ci
script:
  - npm run build:prod

branches:
  only:
    - release

deploy:
  provider: pages:git
  edge: true
  deploy_key: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: release